# Generated by Django 4.0.6 on 2022-08-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
