# Generated by Django 4.0.6 on 2022-10-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_teacher_class_model_teacher_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
