# Generated by Django 4.0.6 on 2022-10-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_teacher_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='status',
        ),
    ]
