# Generated by Django 4.0.6 on 2022-10-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_alter_teacher_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=2000)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class_model',
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_model',
            field=models.ManyToManyField(to='teacher.tag'),
        ),
    ]
