# Generated by Django 4.0.6 on 2022-10-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_tag_remove_teacher_class_model_teacher_class_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scratch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('iframe', models.TextField()),
            ],
        ),
    ]
