# Generated by Django 4.0.6 on 2022-10-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_scratch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scratch',
        ),
    ]
