# Generated by Django 4.0.6 on 2023-04-09 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
