# Generated by Django 4.0.6 on 2022-10-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='date_now',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
