# Generated by Django 4.0.6 on 2022-10-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_course_date_course_date_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_now',
        ),
    ]
