# Generated by Django 4.0.6 on 2023-05-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_course_limited_mins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='docs',
            options={'ordering': ['created_at']},
        ),
    ]
