# Generated by Django 4.0.6 on 2023-05-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_roommember_userpassnormal_alter_course_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPassNormal',
        ),
    ]
