# Generated by Django 4.0.6 on 2022-09-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='atempt',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
