# Generated by Django 4.0.6 on 2023-05-26 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0006_docs_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='owner',
        ),
        migrations.AddField(
            model_name='docs',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
