# Generated by Django 4.0.6 on 2022-10-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_course_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
    ]
