# Generated by Django 4.0.6 on 2023-01-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_classmate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classmate',
        ),
        migrations.AlterField(
            model_name='docs',
            name='name',
            field=models.CharField(default='Hướng dẫn sử dụng GeniDev để phục vụ học tập', max_length=1000),
        ),
        migrations.AlterField(
            model_name='docs',
            name='slug',
            field=models.SlugField(default='huongdansudung', max_length=200),
        ),
        migrations.AlterField(
            model_name='docs',
            name='title',
            field=models.CharField(default='Hướng dẫn sử dụng GeniDev', max_length=100),
        ),
    ]
