# Generated by Django 4.0.6 on 2022-10-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_scratchdocs_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='video_iframe',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scratchdocs',
            name='iframe',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
