# Generated by Django 4.0.6 on 2023-04-09 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='series',
        ),
    ]
