# Generated by Django 4.0.6 on 2023-04-09 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_classroom_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Student'},
        ),
    ]
