# Generated by Django 4.0.6 on 2023-04-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_classroom_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
