# Generated by Django 4.0.6 on 2022-10-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='student_model',
        ),
        migrations.AddField(
            model_name='parents',
            name='student_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Studentworkes', to='student.student', verbose_name='Student_workes'),
        ),
    ]
