# Generated by Django 4.0.6 on 2022-10-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
        ('parents', '0002_remove_parents_student_model_parents_student_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='student_model',
        ),
        migrations.AddField(
            model_name='parents',
            name='student_model',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
