# Generated by Django 4.0.6 on 2022-10-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
        ('parents', '0003_remove_parents_student_model_parents_student_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='student_model',
        ),
        migrations.AddField(
            model_name='parents',
            name='student_model',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
