# Generated by Django 4.0.6 on 2022-11-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='image/student.png', null=True, upload_to='profile_pic/Student/'),
        ),
    ]
