# Generated by Django 4.0.6 on 2023-04-09 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_remove_teacher_class_model_teacher_class_model'),
        ('student', '0003_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='teacher.teacher', verbose_name='Series'),
        ),
    ]
