# Generated by Django 4.0.6 on 2023-04-09 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_classroom'),
        ('student', '0004_student_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='teacher.classroom', verbose_name='Series'),
        ),
    ]
