# Generated by Django 4.0.6 on 2023-04-09 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
    ]
