# Generated by Django 4.0.6 on 2023-04-09 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_alter_classroom_author'),
        ('student', '0006_remove_student_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.classroom', verbose_name='Series'),
        ),
    ]
